name: Publish to S3 bucket and launch tests Workflow

on:
  workflow_dispatch:
  push:

env:
  AWS_REGION     : "eu-west-1"
  AWS_S3_SCORING_STATUS_PATH: "s3://dev-tools-project-octocat-bucket/scoring/status-files/"
  GHE_TOKEN      : ${{ secrets.GHE_TOKEN }}
  GHE_URL        : "https://github.tools.digital.engie.com"
  GHE_OWNER      : "GBSEngieDigitalWalnut"
  GHE_REPO       : "Sitecheck"
  GHE_WORKFLOW   : "sitecheck.yml"
  CITY: ${{vars.CITY || github.event.repository.name}}

jobs:
  publish-and-trigger:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::644297085323:role/tools-octocat
          aws-region: ${{ env.AWS_REGION }}

      - name: Update status json file to BUILD_IN_PROGRESS
        run: |
          echo '{
            "status": "BUILD_IN_PROGRESS"
          }' > ${{ env.CITY }}.json
          aws s3 cp ${{ env.CITY }}.json ${{ env.AWS_S3_SCORING_STATUS_PATH }}

      - name: Set VITE_SITE_NAME, AWS_S3,FQDN & TEAM variables
        run: |
          echo "VITE_SITE_NAME=${{ env.CITY }}" >> $GITHUB_ENV
          echo "AWS_S3_SITE=s3://dev-tools-project-octocat-bucket/websites/${{ env.CITY }}/" >> $GITHUB_ENV
          echo "TEST_URL=https://${{ env.CITY }}-thunder.dev.tools.digital.engie.com/?lang=el" >> $GITHUB_ENV

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20      

      - name: Install pnpm
        run: npm install -g pnpm
   
      - name: build website
        run: |
          pnpm install
          pnpm run build

      - name: Update status json file to BUILD_FAILED
        if: failure()
        run: |
          echo '{
            "status": "BUILD_FAILED"
          }' > ${{ env.CITY }}.json
          aws s3 cp ${{ env.CITY }}.json ${{ env.AWS_S3_SCORING_STATUS_PATH }}

      - name: Upload website's sources to S3
        run: |
          cd ./dist
          pwd
          ls -l
          aws s3 rm ${{ env.AWS_S3_SITE }} --recursive
          aws s3 cp . ${{ env.AWS_S3_SITE }} --recursive --exclude ".git/*"

      - name: Update status json file to WAITING_FOR_TEST
        run: |
          echo '{
            "status": "WAITING_FOR_TEST"
          }' > ${{ env.CITY }}.json
          aws s3 cp ${{ env.CITY }}.json ${{ env.AWS_S3_SCORING_STATUS_PATH }}

      - name: Trigger test workflow	  
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.GHE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ env.GHE_URL }}/api/v3/repos/${{ env.GHE_OWNER }}/${{ env.GHE_REPO }}/actions/workflows/${{ env.GHE_WORKFLOW }}/dispatches \
            -d '{"ref":"main","inputs":{"url":"${{ env.TEST_URL }}","team":"${{ env.CITY }}","challenge":"thunder"}}'          
